// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOv_wX1Jb8tBitMgQ_Sb5H1_FcArGAYk8',
    appId: '1:150116000181:web:b626ae235e9723296ab9fc',
    messagingSenderId: '150116000181',
    projectId: 'flutter-crud-practicing',
    authDomain: 'flutter-crud-practicing.firebaseapp.com',
    storageBucket: 'flutter-crud-practicing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBujm89jwMhuLOQTXW_Sfs8oekD-CVAo_Q',
    appId: '1:150116000181:android:519412e2de72895c6ab9fc',
    messagingSenderId: '150116000181',
    projectId: 'flutter-crud-practicing',
    storageBucket: 'flutter-crud-practicing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC21sXCE_zu0x0BjXJhlH-IsyhZnlSVC54',
    appId: '1:150116000181:ios:fc3d45ca2f7c45276ab9fc',
    messagingSenderId: '150116000181',
    projectId: 'flutter-crud-practicing',
    storageBucket: 'flutter-crud-practicing.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );
}
